SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

export PROJECT_DIR_PATH="$(dirname "$SCRIPT_DIR")" # path to directory above

result="${PROJECT_DIR_PATH%"${PROJECT_DIR_PATH##*[!/]}"}"
result="${result##*/}"
result=${result:-/}

export PROJECT_DIR_NAME=$result # name of directory above

echo
echo "SETTING ENVIRONMENT VARIABLES FOR PROJECT DEPLOYMENT..."
echo
echo PROJECT_DIR_PATH=$PROJECT_DIR_PATH
echo PROJECT_DIR_NAME=$result
echo

# AUCTIONS-SERVICE: define and export env vars
export AUCTIONS_SERVICE_DIR_NAME="auctions-service"
export AUCTIONS_SERVICE_DIR_PATH=$PROJECT_DIR_PATH/$AUCTIONS_SERVICE_DIR_NAME

# display
echo $AUCTIONS_SERVICE_DIR_NAME
echo 
echo AUCTIONS_SERVICE_DIR_NAME=$AUCTIONS_SERVICE_DIR_NAME
echo AUCTIONS_SERVICE_DIR_PATH=$PROJECT_DIR_PATH/$AUCTIONS_SERVICE_DIR_NAME
echo

# CLOSED-AUCTIONS-SERVICE: define and export env vars
export CLOSED_AUCTION_METRICS_SERVICE_DIR_NAME="closed-auction-metrics"
export CLOSED_AUCTION_METRICS_SERVICE_DIR_PATH=$PROJECT_DIR_PATH/$CLOSED_AUCTION_METRICS_SERVICE_DIR_NAME

# display 
echo $CLOSED_AUCTION_METRICS_SERVICE_DIR_NAME
echo 
echo CLOSED_AUCTION_METRICS_SERVICE_DIR_NAME=$CLOSED_AUCTION_METRICS_SERVICE_DIR_NAME
echo CLOSED_AUCTION_METRICS_SERVICE_DIR_PATH=$PROJECT_DIR_PATH/$CLOSED_AUCTION_METRICS_SERVICE_DIR_NAME
echo

